export const STARRED = 'STARRED';
export const REQUEST_QUOTE_PENDING = 'REQUEST_QUOTE PENDING'
export const REQUEST_QUOTE_SUCCESS = 'REQUEST_QUOTE SUCCESS'
export const REQUEST_QUOTE_FAILURE = 'REQUEST_QUOTE FAILURE'


export const LANG_CHANGE = 'LANG_CHANGE'

export const DARK_MODE = "DARK_MODE"

export const STORE_AUTH = 'STORE_AUTH'